In [1]:
import numpy as np
import random

In [2]:
# 1. Create a 3x3 matrix array with values ranging from 2 to 10

a = np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [3]:
# 2. Create a numpy array having user input values and convert the integer type to the float type 
# of the elements of the array. 

n = int(input('Enter the number of elements in array '))
list1 = []
for i in range(n):
    ele = int(input('Enter the elements of array '))
    list1.append(ele)
arr1 = np.array(list1, dtype = float)
print('Int to float elements:', arr1)



Enter the number of elements in array 4
Enter the elements of array 1
Enter the elements of array 2
Enter the elements of array 3
Enter the elements of array 4
Int to float elements: [1. 2. 3. 4.]


In [4]:
# 3. Write a Numpy program to append values to the end of an array.

def append_array_value(array, value):
    print('The input array:',array)
    print('The append values:',value)
    arr = np.append(array, value)
    print('The new array:',arr)
arr1 = np.array([10,20,30])
append_array_value(arr1, [40,50,60,70,80,90])

The input array: [10 20 30]
The append values: [40, 50, 60, 70, 80, 90]
The new array: [10 20 30 40 50 60 70 80 90]


In [5]:
# 4. Create two numpy arrays and add the elements of both the arrays and store the result in sumArray

arr1 = np.array([i for i in range(10)])
arr2 = arr1*2
print('First Array:',arr1)
print('Second Array:',arr2)
sumArray = np.sum([arr1, arr2], axis = 0)
sumArray

First Array: [0 1 2 3 4 5 6 7 8 9]
Second Array: [ 0  2  4  6  8 10 12 14 16 18]


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [6]:
# 5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform 
# the following tasks:
array1 = np.arange(10,91,10).reshape(3,3)
print(array1)
# a. Extract the 1st row from the array.
print('The 1st row of the array is',array1[0])
# b. Extract the last element from the array
print('The last elements of array is',array1[2,2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
The 1st row of the array is [10 20 30]
The last elements of array is 90
