In [1]:
import numpy as np

In [2]:
# 1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a
# Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5)

def create_array(shape, value):
    arr = np.full(shape, value)
    print(arr)
create_array((3,3),5)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [3]:
# 2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

def sum_arrays(list1):
    s_a = np.array(list1)
    print(s_a)
    s_n_a = np.sum(s_a,axis = 0)
    print(s_n_a)
list1 = [[1,2,3],[2,3,4],[4,4,5]]
sum_arrays(list1)

[[1 2 3]
 [2 3 4]
 [4 4 5]]
[ 7  9 12]


In [4]:
# 3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
# numbers N and M. The method should return the top-left N X M sub matrix.

def top_left_matrix(n_m_array):
    arr = n_m_array[:2,:2]
    return arr
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
top_left_matrix(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[1, 2],
       [4, 5]])

In [5]:
# 4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two
# numbers N and M The method should return the bottom-right N X M sub matrix

def top_right_matrix(n_m_array):
    i, j = n_m_array.shape
    arr = n_m_array[(i-2):i,(j-2):(j+1)]
    return arr
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)
top_right_matrix(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 8,  9],
       [11, 12]])

In [6]:
# 5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method
# should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's
# standard deviation as values
a = np.array([1,2,3,4,5,6])
def mean_std(array):
    return {'mean': array.mean(),
            'std_dev': array.std()
        }
mean_std(a)

{'mean': 3.5, 'std_dev': 1.707825127659933}