In [1]:
# 1. Create a list containing squares of numbers from 1 to 10 (HINT: use List Comprehension).

square = [x**2 for x in range(1,11)]
square

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [2]:
# 2. Write a Function to check if year number is a leap year.

def is_leap_year(year):
    if year % 4 == 0:
        if year % 100 == 0:
            if year % 400 == 0:
                print("Leap year")
            else:
                print("Not leap year")
        else:
            print("Leap year")
    else:
        print("Not leap year")

In [3]:
is_leap_year(2226)

Not leap year


In [4]:
# 3. Write a Function to take an array and return another array that 
# contains the members of first array that are even.

import numpy as np
def even_array_generator(array):
    even_array = []
    for i in array:
        if i % 2 == 0:
            even_array.append(i)
        x = np.array(even_array)
    return x

In [5]:
list1 = np.array([x for x in range(11)])
print(list1)
even_array_generator(list1)

[ 0  1  2  3  4  5  6  7  8  9 10]


array([ 0,  2,  4,  6,  8, 10])

In [6]:
# 4. Write a Function that takes 2 arrays and prints the members of first array 
# that are present of second array. (HINT: use Membership Comprehension)

def finding_elements(arr1, arr2):
    for i in arr1:
        if i in arr2:
            print(i)

In [8]:
arr3 = np.array([i for i in range(11)])
arr4 = arr3*2
print(arr3)
print(arr4)
finding_elements(arr3, arr4)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
0
2
4
6
8
10
